#!/usr/bin/env bash

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

if [ ! -e "${GRAALVM_HOME}/bin/native-image" ]; then
    echo "Your ${GRAALVM_HOME} does not have native-image, aborting."
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

MEMBRANE_VERSION=0.11.111-beta    #$(cat resources/CLJ_KONDO_VERSION)

lein with-profiles +clojure-1.10.3 "do" clean, uberjar

args=( "-jar" "target/membrane-$MEMBRANE_VERSION-standalone.jar"
       "-H:+ReportExceptionStackTraces"
       "--verbose"
       "--no-fallback"
       "--initialize-at-build-time"
       "--initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher"
       "--initialize-at-run-time=sun.awt.X11.MotifDnDConstants"
       "--initialize-at-run-time=sun.awt.X11.WindowPropertyGetter"
       "--initialize-at-run-time=sun.awt.X11.XDataTransferer"
       "--initialize-at-run-time=sun.awt.X11.XDnDConstants"
       "--initialize-at-run-time=sun.awt.X11.XSelection"
       "--initialize-at-run-time=sun.awt.X11.XSystemTrayPeer"
       "--initialize-at-run-time=sun.awt.X11.XToolkitThreadBlockedHandler"
       "--initialize-at-run-time=sun.awt.X11.XWindow"
       "--initialize-at-run-time=sun.awt.X11.XWM"
       "--initialize-at-run-time=sun.awt.X11GraphicsConfig"
       "--initialize-at-run-time=sun.awt.X11InputMethodBase"
       "-J-Xmx3g" "$@")
# "--initialize-at-run-time=sun.awt.X11" causes sun.awt.X11.XToolkit to complain about initialization at run time.
# "--initialize-at-run-time=sun.awt.dnd" causes a similar complaint.
# I OFFICIALLY GOT STUCK: ##############################################
# Error message requests that I add the option
#      "--initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher"
# However, this option is already in place.

if [ "$MEMBRANE_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$MEMBRANE_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+StaticExecutableWithDynamicLibC")
    fi
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"
