#!/usr/bin/env bash

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

if [ ! -e "${GRAALVM_HOME}/bin/native-image" ]; then
    echo "Your ${GRAALVM_HOME} does not have native-image, aborting."
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

MEMBRANE_VERSION=0.11.111    #$(cat resources/CLJ_KONDO_VERSION)

lein with-profiles +clojure-1.10.3 "do" clean, uberjar

args=( "-jar" "target/membrane-$MEMBRANE_VERSION-standalone.jar"
       "-H:+ReportExceptionStackTraces"
       "--verbose"
       "--no-fallback"
       "-J-Xmx3g" "$@")

if [ "$MEMBRANE_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$MEMBRANE_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+StaticExecutableWithDynamicLibC")
    fi
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"
